from pathlib import Path

def rep(path, old, new):
    p=Path(path); s=p.read_text(encoding='utf-8')
    if old not in s: raise RuntimeError(f'block missing: {path}: {old[:70]!r}')
    p.write_text(s.replace(old,new,1),encoding='utf-8')

svc='Agent/chatpass_agent/src/platform/windows/windows_service.cpp'
chat='Agent/chatpass_agent/src/ui/native_chat_window.cpp'
view='Viewer/chatpass_viewer/src/app/viewer_app.cpp'
files='Viewer/chatpass_viewer/web/file_browser.html'

# Endpoint banner -> native Chat must explicitly show an already-connected helper.
rep(svc,'                        EnsureChatOverlay(ctx.sessionId, ctx.sessionJob,','                        ChatOverlayState* overlay = EnsureChatOverlay(ctx.sessionId, ctx.sessionJob,')
rep(svc,'                            });\n                    }\n\n                    if (ConsumePresenceBannerAction(ctx.sessionId, false)) {','                            });\n                        if (overlay) {\n                            {\n                                std::lock_guard<std::mutex> lock(overlay->mu);\n                                overlay->pendingToOverlay.push_back(json{{"type", "show"}, {"session_id", ctx.sessionId}}.dump());\n                            }\n                            FlushQueuedChatToOverlay(overlay);\n                        }\n                    }\n\n                    if (ConsumePresenceBannerAction(ctx.sessionId, false)) {')

# Observe actual endpoint monitor geometry; do not change Windows display mode.
rep(svc,'                auto nextMonitorPoll = std::chrono::steady_clock::now() + std::chrono::seconds(1);\n                auto nextSecurePoll = std::chrono::steady_clock::now() + std::chrono::milliseconds(25);','                auto nextMonitorPoll = std::chrono::steady_clock::now() + std::chrono::seconds(1);\n                std::string lastMonitorGeometry;\n                auto nextSecurePoll = std::chrono::steady_clock::now() + std::chrono::milliseconds(25);')
rep(svc,'                            msg["monitors"] = json::array();\n                            for (int i = 0; i < count; ++i) {\n                                const auto mi = ctx.normalInputPipe.GetMonitorInfo(i);\n                                msg["monitors"].push_back({\n                                    {"index", i}, {"name", std::string("Monitor ") + std::to_string(i + 1)},\n                                    {"x", mi.x}, {"y", mi.y}, {"w", mi.w}, {"h", mi.h}, {"primary", mi.primary != 0}\n                                    });\n                            }\n                            signaling_->send(msg.dump());','                            msg["monitors"] = json::array();\n                            std::ostringstream geometry;\n                            geometry << "count=" << count;\n                            for (int i = 0; i < count; ++i) {\n                                const auto mi = ctx.normalInputPipe.GetMonitorInfo(i);\n                                msg["monitors"].push_back({\n                                    {"index", i}, {"name", std::string("Monitor ") + std::to_string(i + 1)},\n                                    {"x", mi.x}, {"y", mi.y}, {"w", mi.w}, {"h", mi.h}, {"primary", mi.primary != 0}\n                                    });\n                                geometry << " m" << i << "=" << mi.x << "," << mi.y << "," << mi.w << "x" << mi.h << (mi.primary != 0 ? ":primary" : "");\n                            }\n                            const std::string geometryText = geometry.str();\n                            if (geometryText != lastMonitorGeometry) {\n                                LogI("[display-geometry] session=" + ctx.sessionId + " " + geometryText);\n                                lastMonitorGeometry = geometryText;\n                            }\n                            signaling_->send(msg.dump());')

# Remote-device native Chat: DPI/work-area responsive and Windows 11 rounded.
rep(chat,'#include <windowsx.h>\n','#include <windowsx.h>\n#include <dwmapi.h>\n')
rep(chat,'    void NativeChatWindow::UiThreadMain() {\n        uiThreadId_ = GetCurrentThreadId();','    void NativeChatWindow::UiThreadMain() {\n        uiThreadId_ = GetCurrentThreadId();\n        SetThreadDpiAwarenessContext(DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2);')
rep(chat,'            440,\n            420,','            420,\n            560,')
rep(chat,'        font_ = CreateFontW(\n            -16, 0, 0, 0, FW_NORMAL, FALSE, FALSE, FALSE,\n            DEFAULT_CHARSET, OUT_OUTLINE_PRECIS, CLIP_DEFAULT_PRECIS, CLEARTYPE_QUALITY,\n            VARIABLE_PITCH, L"Segoe UI");','        const UINT dpi = GetDpiForWindow(hwnd_);\n        font_ = CreateFontW(-MulDiv(10, static_cast<int>(dpi), 72), 0, 0, 0, FW_NORMAL, FALSE, FALSE, FALSE,\n            DEFAULT_CHARSET, OUT_OUTLINE_PRECIS, CLIP_DEFAULT_PRECIS, CLEARTYPE_QUALITY,\n            VARIABLE_PITCH, L"Segoe UI Variable");\n        const int cornerPreference = 2;\n        DwmSetWindowAttribute(hwnd_, 33, &cornerPreference, sizeof(cornerPreference));')
rep(chat,'        const int margin = 12;\n        const int composerHeight = 32;\n        const int buttonWidth = 84;','        const float scale = std::max(1.0f, static_cast<float>(GetDpiForWindow(hwnd_)) / 96.0f);\n        const auto px = [scale](int dip) { return std::max(1, static_cast<int>(dip * scale)); };\n        const int margin = px(12);\n        const int composerHeight = px(40);\n        const int buttonWidth = px(82);')
rep(chat,'        const int workW = std::max(320, workRight - workLeft);\n        const int workH = std::max(260, workBottom - workTop);','        const int workW = std::max(1, workRight - workLeft);\n        const int workH = std::max(1, workBottom - workTop);')
rep(chat,'                if (type == "chat_message") {','                if (type == "show") { window.Show(); continue; }\n                if (type == "chat_message") {')

# Technician Viewer Chat: responsive host, banner accent, and renderer remains source-of-truth (no duplicate local echo).
rep(view,'                    chat.set_size(380, 560, WEBVIEW_HINT_NONE);','                    chat.set_size(420, 620, WEBVIEW_HINT_NONE);')
rep(view,"try{if(window.hi5ChatSend)await window.hi5ChatSend(body);add({sender:'tech',display_name:'Technician',body});}catch(e){console.error(e)}","try{if(window.hi5ChatSend)await window.hi5ChatSend(body);}catch(e){console.error(e)}")
rep(view,'background:linear-gradient(135deg,#6366f1,#06b6d4)','background:#2563eb')
rep(view,'background:linear-gradient(135deg,#4f46e5,#2563eb)','background:#2563eb')
rep(view,'background:#6366f1;color:#fff','background:#2563eb;color:#fff')
rep(view,'                        const int width = 380;\n                        const int height = 560;\n                        RECT work{};\n                        SystemParametersInfoW(SPI_GETWORKAREA, 0, &work, 0);\n                        const int x = work.right - width - 24;\n                        const int y = work.bottom - height - 24;\n                        MoveWindow(hwnd, x > 0 ? x : 40, y > 0 ? y : 40, width, height, TRUE);','                        RECT work{};\n                        SystemParametersInfoW(SPI_GETWORKAREA, 0, &work, 0);\n                        const int workWidth = static_cast<int>(work.right - work.left);\n                        const int workHeight = static_cast<int>(work.bottom - work.top);\n                        const int width = std::min(420, std::max(300, workWidth - 24));\n                        const int height = std::min(620, std::max(320, workHeight - 24));\n                        chat.set_size(std::min(300, width), std::min(320, height), WEBVIEW_HINT_MIN);\n                        const int x = static_cast<int>(work.right) - width - 12;\n                        const int y = static_cast<int>(work.bottom) - height - 12;\n                        MoveWindow(hwnd, std::max<int>(work.left, x), std::max<int>(work.top, y), width, height, TRUE);')

# File Browser host and DOM can both shrink; CSS stacks panes below 840px.
rep(view,'                        const int maxWidth = std::max<int>(860, workWidth);\n                        const int maxHeight = std::max<int>(560, workHeight);\n                        const int width = std::min<int>(1120, maxWidth);\n                        const int height = std::min<int>(740, maxHeight);\n                        file.set_size(900, 600, WEBVIEW_HINT_MIN);','                        const int width = std::min<int>(1120, std::max<int>(320, workWidth - 24));\n                        const int height = std::min<int>(740, std::max<int>(300, workHeight - 24));\n                        file.set_size(std::min<int>(420, width), std::min<int>(360, height), WEBVIEW_HINT_MIN);')
p=Path(files); s=p.read_text(encoding='utf-8')
s=s.replace('<title>Hi5Tech File Browser</title>','<title>Hi5Central File Browser</title>',1)
s=s.replace(':root{color-scheme:dark;--bg:#0b1020;--panel:#111827;--panel2:#0f172a;--card:#162033;--border:rgba(148,163,184,.22);--text:#e5e7eb;--muted:#94a3b8;--accent:#6366f1;--accent2:#22c55e;--danger:#ef4444;--warn:#f59e0b;--shadow:0 18px 45px rgba(0,0,0,.35)}',':root{color-scheme:light;--bg:#f7f9fc;--panel:#f8fafc;--panel2:#f8fafc;--card:#fff;--border:#dbe3ec;--text:#111827;--muted:#64748b;--accent:#2563eb;--accent2:#22c55e;--danger:#dc2626;--warn:#f59e0b;--shadow:0 18px 44px rgba(15,23,42,.12)}',1)
s=s.replace('.shell{height:100vh;min-width:860px;','.shell{height:100vh;min-width:0;',1)
s=s.replace('grid-template-columns:minmax(380px,1fr) minmax(380px,1fr);','grid-template-columns:minmax(0,1fr) minmax(0,1fr);',1)
s=s.replace('background:linear-gradient(135deg,var(--accent),#8b5cf6)','background:var(--accent)',1)
s=s.replace('</style>','@media(max-width:840px){.layout{grid-template-columns:1fr;overflow:auto}.pane{min-height:340px}.pathRow{flex-wrap:wrap}.pathInput{flex-basis:100%}.pathRow .btn{flex:1}.sub{display:none}}@media(max-width:520px){.layout{padding:6px;gap:6px}.pane{min-height:300px}.quick{overflow:auto;flex-wrap:nowrap}.quick button{flex:0 0 auto}.meta{display:none}.header{padding:8px}.status{font-size:10px}}</style>',1)
p.write_text(s,encoding='utf-8')
print('UI + display diagnostics changes applied')
